---
- name: Configurer Nginx
  hosts: lbservers
  become: yes
  tasksO:
    - name: Installer Nginx
      apt:
        name: nginx
        state: present
    - name: Déployer la configuration de Nginx
      template:
        src: /path/to/nginx.conf.j2
        dest: /etc/nginx/sites-available/default
    - name: Redémarrer Nginx
      systemd:
        name: nginx
        state: restarted

