---
- name: Déploiement du serveur web avec répertoire personnalisé et FQDN
  hosts: webservers
  become: yes  # Exécuter les commandes avec sudo

  vars:
    fqdn: "www.exemple.com"
    web_root: "/var/www/mon-site"

  tasks:
    - name: Mettre à jour les paquets (Debian/Ubuntu)
      apt:
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: Installer Nginx
      package:
        name: nginx
        state: present

    - name: Créer le répertoire du site
      file:
        path: "{{ web_root }}"
        state: directory
        owner: www-data
        group: www-data
        mode: "0755"

    - name: Déployer la page d'accueil
      copy:
        content: "<h1>Bienvenue sur {{ fqdn }}</h1>"
        dest: "{{ web_root }}/index.html"
        owner: www-data
        group: www-data
        mode: "0644"

    - name: Configurer le Virtual Host Nginx
      template:
        src: templates/nginx_vhost.j2
        dest: "/etc/nginx/sites-available/{{ fqdn }}"
      notify: Restart Nginx

    - name: Activer le Virtual Host
      file:
        src: "/etc/nginx/sites-available/{{ fqdn }}"
        dest: "/etc/nginx/sites-enabled/{{ fqdn }}"
        state: link
      notify: Restart Nginx

    - name: Vérifier la configuration Nginx
      command: nginx -t
      register: nginx_test
      changed_when: false

    - name: Afficher le résultat du test Nginx
      debug:
        var: nginx_test.stdout_lines

    - name: Ouvrir le port 80 (HTTP)
      ufw:
        rule: allow
        port: "80"
        proto: tcp
      when: ansible_os_family == "Debian"

  handlers:
    - name: Restart Nginx
      service:
        name: nginx
        state: restarted

