---
- name: Configurer les serveurs Web
  hosts: webservers
  become: yes
  tasks:
    - name: Installer Apache
      apt:
        name: apache2
        state: present
    - name: Installer PHP
      apt:
        name: php-fpm
        state: present
    - name: Installer MySQL
      apt:
        name: mysql-server
        state: present

